https://www.datascience.com/blog/7-methods-to-fit-linear-model-python

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

## read in data

In [2]:
# read data into a DataFrame
data = pd.read_csv('http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv', index_col=0)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

https://en.wikipedia.org/wiki/Ordinary_least_squares


__Linear Modeling Function:__

</br>

${\displaystyle y_{i}=\beta _{1}x_{i1}+\beta _{2}x_{i2}+\cdots +\beta _{p}x_{ip}+\varepsilon _{i}}$

</br>

As a rule, the constant term is always included in the set of regressors $X$, say, by taking $x_{i1} = 1$ for all observations $i = 1, …, n$. The coefficient $\beta_1$ corresponding to this regressor is called the intercept.



__In Vector Form:__

</br>

${\displaystyle y_{i}=x_{i}^{T}\beta +\varepsilon _{i}\,}$

the $ε_i$'s are unobserved scalar random variables (errors) which account for influences upon the responses yi from sources other than the explanators $x_i$. 
$x_{i}$ is a column vector of the ith observations of all the explanatory variables.

__In Matrix Form:__

</br>

${\displaystyle {\hat {\boldsymbol {\beta }}}=(\mathbf {X} ^{\mathsf {T}}\mathbf {X} )^{-1}\mathbf {X} ^{\mathsf {T}}\mathbf {y}}$



${\displaystyle \mathbf {X} ={\begin{bmatrix}X_{11}&X_{12}&\cdots &X_{1p}\\X_{21}&X_{22}&\cdots &X_{2p}\\\vdots &\vdots &\ddots &\vdots \\X_{N1}&X_{N2}&\cdots &X_{Np}\end{bmatrix}},\qquad {\boldsymbol {\beta }}={\begin{bmatrix}\beta _{1}\\\beta _{2}\\\vdots \\\beta _{p}\end{bmatrix}},\qquad \mathbf {y} ={\begin{bmatrix}y_{1}\\y_{2}\\\vdots \\y_{N}\end{bmatrix}}.}$


N is the number of observations and p is the number of features, predictors, independent variables, regressors, etc...
The terms representing the variables in the training data set have many names. 

$\beta$ is the coefficient vector.

$y$ is the response vector, or vector of dependent variables. When you are training a model, $y$ is the response that that model should be able to closely predict.  

#### The below notes are from Wikipedia, so make sure they match the book. 

Suppose $\beta$ is a "candidate" value for the parameter vector $\boldsymbol{\beta}$. The quantity $y_i − x_i^T \beta$, called the residual for the _i_th observation, measures the vertical distance between the data point ($x_i$, $y_i$) and the hyperplane $y = x^T \beta$, and thus assesses the degree of fit between the actual data and the model. The sum of squared residuals (SSR) (also called the error sum of squares (ESS) or residual sum of squares (RSS)) is a measure of the overall model fit:


${\displaystyle RSS(\beta)=\sum _{i=1}^{N}(y_{i}-x_{i}^{\mathrm {T} }\beta)^{2} = (\boldsymbol{y}-\boldsymbol{X}\beta)^{\mathrm {T} }(\boldsymbol{y}-\boldsymbol{X}\beta)}$

The goal is to find the set of coefficients $\beta$ that minimize the residual sum of squares (RSS). 



${\displaystyle RSS(\beta)= (\boldsymbol{y}-\boldsymbol{X}\beta)^{\mathrm {T} }(\boldsymbol{y}-\boldsymbol{X}\beta)}$

${\displaystyle {\hat {\boldsymbol {\beta }}}=(\mathbf {X} ^{\mathsf {T}}\mathbf {X} )^{-1}\mathbf {X} ^{\mathsf {T}}\mathbf {y}}$

In [4]:
xdata = np.asarray(data.TV)

# X = np.vstack([np.ones(len(xdata)), xdata]).T
# X = np.asmatrix(X)

# OR, A BETTER SOLUTION:
X = np.matrix([ np.ones(len(xdata)), xdata ]).T  # shape(200, 2)
y = np.asarray(data.sales)

print(X.shape)            # (200, 2)
print(y.shape)            # (200, )
print(np.vstack(y).shape) # (200, 1)

beta = ((X.T * X)**-1) * X.T * np.vstack(y)
beta



(200, 2)
(200,)
(200, 1)


matrix([[7.03259355],
        [0.04753664]])

In [7]:
RSS = (np.vstack(y) - X * beta).T * (np.vstack(y) - X * beta)
RSS

matrix([[2102.53058313]])

In [8]:
np.sqrt(float(RSS))

45.85335956210135

#### Reduced Chi-Squared: RSS/n-p

[Projection Matrix](https://en.wikipedia.org/wiki/Projection_matrix)

[Identity Matrix](https://en.wikipedia.org/wiki/Identity_matrix)

${\displaystyle \mathbf {\hat {y}} =\mathbf {P} \mathbf {y} }$

$P = X(X^TX)^{−1}X^T$

In [36]:
projection_matrix = (X*(X.T*X)**-1) * X.T
identity_matrix = np.identity(n=len(X))

In [37]:
residual_maker_matrix = identity_matrix - projection_matrix

M is the "residual maker matrix"

M = I − P  

I is the identity matrix and P is the projection matrix. Puts a hat onto y.

In [45]:
n,p = X.shape
M = residual_maker_matrix
s_squared = (np.vstack(y).T * M * np.vstack(y))/(n-p)
s_squared  # appears to be same as RSS/(n-p)

matrix([[10.61884133]])

In [46]:
RSS/(n-p)

matrix([[10.61884133]])

In [43]:
chi_squared = ((n-p)/n) * float(s_squared)
chi_squared

10.512652915656668

In [47]:
np.sqrt(10.512652915656668)

3.242322148654675

In [9]:
import statsmodels.formula.api as smf

In [69]:
?smf.ols

In [10]:
result = smf.ols(formula='sales ~ TV', data=data).fit()

In [11]:
result.params

Intercept    7.032594
TV           0.047537
dtype: float64

In [12]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                  sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Sat, 12 Jan 2019   Prob (F-statistic):           1.47e-42
Time:                        23:27:47   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.0

In [13]:
print(result.summary2())

                 Results: Ordinary least squares
Model:              OLS              Adj. R-squared:     0.610    
Dependent Variable: sales            AIC:                1042.0913
Date:               2019-01-12 23:27 BIC:                1048.6880
No. Observations:   200              Log-Likelihood:     -519.05  
Df Model:           1                F-statistic:        312.1    
Df Residuals:       198              Prob (F-statistic): 1.47e-42 
R-squared:          0.612            Scale:              10.619   
--------------------------------------------------------------------
              Coef.    Std.Err.      t      P>|t|    [0.025   0.975]
--------------------------------------------------------------------
Intercept     7.0326     0.4578   15.3603   0.0000   6.1297   7.9355
TV            0.0475     0.0027   17.6676   0.0000   0.0422   0.0528
------------------------------------------------------------------
Omnibus:              0.531         Durbin-Watson:           1.935
Pro

## Scikit-learn

In [285]:
from sklearn.linear_model import LinearRegression

In [286]:
linreg = LinearRegression( )

In [287]:
ones = np.ones(shape=len(data.TV))   # works
zeros = np.zeros(shape=len(data.TV)) # works
empty = np.empty(shape=len(data.TV)) # works

xdata = np.asarray(data.TV)

# ALL 3 OF THESE WORK THE SAME. THE SECOND COEFF WILL BE 0 SINCE ITS A DUMMY ARRAY IN X. 

X = np.asarray(list(zip(xdata, ones)))  # works
#X = np.asarray(list(zip(xdata, zeros))) # works
#X = np.asarray(list(zip(xdata, empty))) # works

y = np.asarray(data.sales)

In [288]:
result = linreg.fit(X, y) 

# print the intercept and coefficients
print(result.intercept_)
print(result.coef_)

7.0325935491276965
[0.04753664 0.        ]


In [293]:
result.singular_

array([1211.12304443,    0.        ])

## Using Matrices/Vector Algebra

See [Wikipedia page](https://en.wikipedia.org/wiki/Ordinary_least_squares) under the Linear Model section and Matrix/vector formulation subsection. 

${\displaystyle {\hat {\boldsymbol {\beta }}}=(\mathbf {X} ^{\rm {T}}\mathbf {X} )^{-1}\mathbf {X} ^{\rm {T}}\mathbf {y} .}$

${\displaystyle \mathbf {X} ={\begin{bmatrix}X_{11}&X_{12}&\cdots &X_{1p}\\X_{21}&X_{22}&\cdots &X_{2p}\\\vdots &\vdots &\ddots &\vdots \\X_{n1}&X_{n2}&\cdots &X_{np}\end{bmatrix}},\qquad {\boldsymbol {\beta }}={\begin{bmatrix}\beta _{1}\\\beta _{2}\\\vdots \\\beta _{p}\end{bmatrix}},\qquad \mathbf {y} ={\begin{bmatrix}y_{1}\\y_{2}\\\vdots \\y_{n}\end{bmatrix}}.}$

xdata = np.asarray(data.TV)

# X = np.vstack([xdata, np.ones(len(xdata))]).T
# X = np.asmatrix(X)

# OR, A BETTER SOLUTION:
X = np.matrix([xdata, np.ones(len(xdata))]).T  # shape(200, 2)
y = np.asarray(data.sales)

print(X.shape)            # (200, 2)
print(y.shape)            # (200, )
print(np.vstack(y).shape) # (200, 1)

beta = ((X.T * X)**-1) * X.T * np.vstack(y)
beta

### USING NUMPY ARRAY DOENS'T WORK FOR X, EVENTHOUGH IT HAS THE SAME SHAPE AND LOOKS THE SAME. 

In [275]:
X.shape

(200, 2)

In [276]:
X

matrix([[230.1,   1. ],
        [ 44.5,   1. ],
        [ 17.2,   1. ],
        [151.5,   1. ],
        [180.8,   1. ],
        [  8.7,   1. ],
        [ 57.5,   1. ],
        [120.2,   1. ],
        [  8.6,   1. ],
        [199.8,   1. ],
        [ 66.1,   1. ],
        [214.7,   1. ],
        [ 23.8,   1. ],
        [ 97.5,   1. ],
        [204.1,   1. ],
        [195.4,   1. ],
        [ 67.8,   1. ],
        [281.4,   1. ],
        [ 69.2,   1. ],
        [147.3,   1. ],
        [218.4,   1. ],
        [237.4,   1. ],
        [ 13.2,   1. ],
        [228.3,   1. ],
        [ 62.3,   1. ],
        [262.9,   1. ],
        [142.9,   1. ],
        [240.1,   1. ],
        [248.8,   1. ],
        [ 70.6,   1. ],
        [292.9,   1. ],
        [112.9,   1. ],
        [ 97.2,   1. ],
        [265.6,   1. ],
        [ 95.7,   1. ],
        [290.7,   1. ],
        [266.9,   1. ],
        [ 74.7,   1. ],
        [ 43.1,   1. ],
        [228. ,   1. ],
        [202.5,   1. ],
        [177. , 

In [277]:
# THIS HAS SHAPE (200, 2). 
X = np.asarray( [xdata, np.ones(len(xdata))] ).T

In [278]:
X.shape

(200, 2)

In [279]:
X

array([[230.1,   1. ],
       [ 44.5,   1. ],
       [ 17.2,   1. ],
       [151.5,   1. ],
       [180.8,   1. ],
       [  8.7,   1. ],
       [ 57.5,   1. ],
       [120.2,   1. ],
       [  8.6,   1. ],
       [199.8,   1. ],
       [ 66.1,   1. ],
       [214.7,   1. ],
       [ 23.8,   1. ],
       [ 97.5,   1. ],
       [204.1,   1. ],
       [195.4,   1. ],
       [ 67.8,   1. ],
       [281.4,   1. ],
       [ 69.2,   1. ],
       [147.3,   1. ],
       [218.4,   1. ],
       [237.4,   1. ],
       [ 13.2,   1. ],
       [228.3,   1. ],
       [ 62.3,   1. ],
       [262.9,   1. ],
       [142.9,   1. ],
       [240.1,   1. ],
       [248.8,   1. ],
       [ 70.6,   1. ],
       [292.9,   1. ],
       [112.9,   1. ],
       [ 97.2,   1. ],
       [265.6,   1. ],
       [ 95.7,   1. ],
       [290.7,   1. ],
       [266.9,   1. ],
       [ 74.7,   1. ],
       [ 43.1,   1. ],
       [228. ,   1. ],
       [202.5,   1. ],
       [177. ,   1. ],
       [293.6,   1. ],
       [206

Computing beta will throw the following error: 

    ValueError: operands could not be broadcast together with shapes (2,200) (200,2) 

In [281]:
beta = ((X.T * X)**-1) * X.T * np.vstack(y)
beta

ValueError: operands could not be broadcast together with shapes (2,200) (200,2) 

#### The matrix:

In [283]:
X = np.matrix([xdata, np.ones(len(xdata))]).T  # shape(200, 2)
X.T * np.vstack(y)

matrix([[482108.34],
        [  2804.5 ]])

#### The array:

In [284]:
X = np.asarray( [xdata, np.ones(len(xdata))] ).T
X.T * np.vstack(y)

ValueError: operands could not be broadcast together with shapes (2,200) (200,1) 